# Funding options for 2020KHODA 🚀

github: 2020khoda

custom:
  - "https://2020khoda.com"
  - "mailto:king2020khoda@gmail.com"
  - "https://t.me/khoda2020"
  - "tel:+989170012020"
  - "tel:+989170062020"
